// ignore_for_file: constant_identifier_names

enum AppException {


  
  // AUTH
  FAILED_TO_CREATE_NEW_USER,
  EMAIL_ALREADY_IN_USE,
  INVALID_EMAIL,
  OPERATION_NOT_ALLOWED,
  WEAK_PASSWORD,
  TOO_MANY_REQUESTS,
  USER_TOKEN_EXPIRED,
  NETWORK_REQUEST_FAILED,


  FAILED_TO_SIGN_IN,
  USER_DISABLED,
  USER_NOT_FOUND,
  WRONG_PASSWORD,
  INVALID_CREDENTIAL,

}
